<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>edi</string>
        <string>hl7</string>
    </array>
    <key>name</key>
    <string>HL7</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^(.*?)(\|)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.hl7</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.hl7</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(\^|&|~)</string>
            <key>name</key>
            <string>string.other.hl7</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(\|)(ADT|MFN|PPR|ORU|ORM|REF|ACK)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.hl7</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.function.hl7</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>name</key>
            <string>constant.character.hl7</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.hl7</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(.*?)</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>\|</string>
            <key>name</key>
            <string>constant.character.hl7</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.hl7</string>
    <key>uuid</key>
    <string>263b608e-ed0c-496a-82db-35d1a6065fd7</string>
</dict>
</plist>
