<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>edi</string>
        <string>hl7</string>
    </array>
    <key>name</key>
    <string>HL7</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>^(.*?)(\|)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.hl7</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.hl7</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>(\^|&|~)</string>
            <key>name</key>
            <string>string.other.hl7</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(\|)(ACK|ADT|BAR|BPS|BRP|BRT|BTS|CCF|CCI|CCM|CCQ|CCR|CCU|CQU|CRM|CSU|DBC|DBU|DEL|DEO|DER|DFT|DPR|DRC|DRG|EAC|EAN|EAR|EHC|ESR|ESU|INR|INU|LSR|LSU|MDM|MFK|MFN|NMD|OMB|OMD|OMG|OMI|OML|OMN|OMP|OMQ|OMS|OPL|OPR|OPU|ORA|ORB|ORD|ORG|ORI|ORL|ORN|ORP|ORS|ORU|ORX|OSM|OSU|OUL|PEX|PGL|PIN|PMU|PPG|PPP|PPR|QBP|QCN|QSB|QSX|QVR|RAS|RDE|RDR|RDS|RDY|REF|RGV|RPA|RPI|RPL|RPR|RQA|RQI|RQP|RRA|RRD|RRE|RRG|RRI|RSP|RTB|SCN|SDN|SDR|SIU|SLN|SLR|SMD|SRM|SRR|SSR|SSU|STC|STI|TCR|TCU|UDM|VXU)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.hl7</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.function.hl7</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\|)</string>
            <key>name</key>
            <string>constant.character.hl7</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>support.function.hl7</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(.*?)</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>\|</string>
            <key>name</key>
            <string>constant.character.hl7</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.hl7</string>
    <key>uuid</key>
    <string>263b608e-ed0c-496a-82db-35d1a6065fd7</string>
</dict>
</plist>
